import MainBodyContents from "@/components/Contents/MainBodyContents";
import BottomNavBar from "@/components/navbar/BottomNavBar";
import TopNavBar from "@/components/navbar/TopNavBar";
import LeftSideNavBar from "@/components/sidebar/LeftSideNavBar";
import RightWidgets from "@/components/Widgets/RightWidgets";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Expere</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="">
          <TopNavBar />
          <BottomNavBar />
          <div className="grid grid-cols-12 py-32 p-8 gap-6">
            <div className="col-span-3 hidden lg:block ">
              <LeftSideNavBar />
            </div>
            <div className="col-span-12 lg:col-span-6">
              <MainBodyContents />
            </div>
            <div className="col-span-3 hidden lg:block ">
              <RightWidgets />
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
