import BottomNavBar from "@/components/navbar/BottomNavBar";
import TopNavBar from "@/components/navbar/TopNavBar";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Expere</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="">
         <TopNavBar />
         <BottomNavBar />
        </div>
      </main>
    </>
  );
}
